- name: NGINX | Adding NGINX signing key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present
 
- name: NGINX | Adding sources.list deb url for NGINX
  lineinfile: dest=/etc/apt/sources.list line="deb http://nginx.org/packages/mainline/ubuntu/ trusty nginx"
 
- name: NGINX Plus | Adding sources.list deb-src url for NGINX
  lineinfile: dest=/etc/apt/sources.list line="deb-src http://nginx.org/packages/mainline/ubuntu/ trusty nginx"
 
- name: NGINX | Updating apt cache
  apt:
    update_cache: yes
 
- name: NGINX | Installing NGINX
  apt:
    pkg: nginx
    state: latest
 
- name: Copying HTML page to NGINX directory
  sudo: yes
  copy:
    src: /home/ahmad/Desktop/DO/html/index.html
    dest: /usr/share/nginx/html
    owner: vagrant
    group: vagrant
    mode: 0777
 
- name: Securing ports 80 and 443 (HTTP HTTPS)
  ufw:
    rule: allow
    port: http
    proto: tcp
  ufw:
    rule: allow
    port: https
    proto: tcp
  ufw:
    rule: allow
    port: ssh
    proto: tcp
 
- name: Copying script to mkdir
  sudo: yes
  copy:
    src: /home/ahmad/Desktop/DO/scripts/create_ssl.sh
    dest: /home
    owner: vagrant
    group: vagrant
    mode: 0777

- name: Executing script
  sudo: yes
  shell: /home/create_ssl.sh
         

- expect:
    command: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/nginx.key -out /etc/nginx/ssl/nginx.crt
    responses:
      Country Name \(2 letter code\) \[AU\]: "US"
      State or Province Name \(full name\) \[Some-State\]: "New Jersey"
      Locality Name \(eg, city\) \[\]: "Clementon"
      Organization Name \(eg, company\) \[Internet Widgits Pty Ltd\]: "NCSU"
      Organizational Unit Name \(eg, section\) \[\]: "DevOps"
      Common Name \(e.g. server FQDN or YOUR name\) \[\]: "192.168.33.10"
      Email Address \[\]: "akhan7@ncsu.edu"
          


- name: NGINX | Starting NGINX
  service:
    name: nginx
    state: started