# /home/ahmad/Desktop/DevOps_Project/ansible-nginx/deploy.yml

- name: Starting the task on host nginx	 
  hosts: nginx
  sudo: yes
  tasks:
    - include: 'tasks/dependencies.yml'
    - include: 'tasks/install_nginx.yml'
    - include: 'tasks/test.yml'

